import { Inject, Injectable, Logger, Optional } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { errorMessage } from '@wispace/bot-common/masking';
import type { ReportClaimRepositoryPort } from '../ports/report-claim.repository.port';
import type { ReportDeliveryPort } from '../ports/report-delivery.port';
import type { ReportSendJobRepositoryPort } from '../ports/report-send-job.repository.port';
import { REPORT_CLAIM_REPOSITORY } from '../ports/report-claim.repository.port';
import { REPORT_DELIVERY_PORT } from '../ports/report-delivery.port';
import { REPORT_SEND_JOB_REPOSITORY } from '../ports/report-send-job.repository.port';
import type {
  ClaimAndSendResult,
  ReportMapping,
} from '../types/report-send-job.types';
import { ReportSendScheduleService } from './report-send-schedule.service';

const DEFAULT_REPORT_CLAIM_LEASE_MS = 2 * 60 * 60 * 1000;

// ponytail: inlined from @wispace/database to break circular dependency
function readReportClaimLeaseMs(configService: ConfigService): number {
  const raw = configService.get<string>('REPORT_CLAIM_STALE_RESET_MS');
  const parsed = raw ? Number(raw) : NaN;
  return Number.isFinite(parsed) && parsed > 0
    ? Math.floor(parsed)
    : DEFAULT_REPORT_CLAIM_LEASE_MS;
}

const ZERO: ClaimAndSendResult = {
  sent: 0,
  skipped: 0,
  deferred: 0,
  windowClosed: 0,
  claimSkipped: 0,
  retryQueued: 0,
  failures: [],
};

export interface ClassifiedError {
  kind: 'retryable' | 'window_closed' | 'skipped' | 'failure';
  message: string;
}

/**
 * Shared claim lifecycle for scheduled report sends — used by Discord and Zalo.
 *
 * The skeleton is: hasSentToday guard → tryClaim → crash-recovery shortcircuit
 * → send → mark/release → error classify → retryable? record job.
 *
 * Platform-specific concerns are injected via callbacks:
 * - `classifyError`: maps exceptions to `{kind, message}`
 * - `platform`: for deliveryKey prefix and outbox
 * - `reportText`: pre-generated by caller (decouples generation from orchestration)
 */
@Injectable()
export class ReportOrchestrationService {
  private readonly logger = new Logger(ReportOrchestrationService.name);

  constructor(
    @Inject(REPORT_CLAIM_REPOSITORY)
    private readonly claimRepo: ReportClaimRepositoryPort,
    @Inject(REPORT_DELIVERY_PORT)
    private readonly delivery: ReportDeliveryPort,
    @Optional()
    @Inject(REPORT_SEND_JOB_REPOSITORY)
    private readonly jobRepo: ReportSendJobRepositoryPort | null,
    private readonly reportSendScheduleService: ReportSendScheduleService,
    private readonly configService: ConfigService,
  ) {}

  async claimAndSend(
    mapping: ReportMapping,
    opts: {
      reportDate: string;
      skipAlreadySentToday: boolean;
      reportText: string;
      examDateForOutbox?: string;
      classifyError?: (error: unknown) => ClassifiedError;
      generateReport?: () => Promise<string>;
    },
  ): Promise<ClaimAndSendResult> {
    const { reportDate, skipAlreadySentToday, examDateForOutbox } = opts;
    const classifyError = opts.classifyError ?? defaultClassifyError;
    const platform = mapping.platform;
    const deliveryKey = `${platform}-report:${mapping.externalUserId}:${reportDate}`;

    // ── Step 1: has-sent-today guard ────────────────────────────────────
    if (skipAlreadySentToday) {
      const alreadySent = await this.claimRepo.hasSentScheduledReportToday(
        mapping.externalUserId,
      );
      if (alreadySent) {
        if (examDateForOutbox && this.jobRepo) {
          await this.jobRepo.markSentByExternalUserExamDate(
            mapping.externalUserId,
            examDateForOutbox,
          );
        }
        return { ...ZERO, skipped: 1 };
      }

      if (mapping.userId) {
        const anySent = await this.claimRepo.hasAnyPlatformSentReportToday(
          mapping.userId,
          reportDate,
        );
        if (anySent) {
          return { ...ZERO, skipped: 1 };
        }
      }
    }

    // ── Step 2: try claim ───────────────────────────────────────────────
    let claimedForSend = false;
    let claimLeaseToken = '';
    let claimDeliveryRecord: string | undefined;
    if (skipAlreadySentToday) {
      const claimed = await this.claimRepo.tryClaimScheduledReport(
        {
          externalUserId: mapping.externalUserId,
          userId: mapping.userId,
          reportDate,
        },
        readReportClaimLeaseMs(this.configService),
      );
      if (!claimed.claimed || !claimed.leaseToken) {
        return { ...ZERO, claimSkipped: 1 };
      }
      claimedForSend = true;
      claimLeaseToken = claimed.leaseToken;
      claimDeliveryRecord =
        typeof claimed.deliveryRecord === 'string'
          ? claimed.deliveryRecord
          : undefined;
    }

    // ── Step 3: crash-recovery shortcircuit (#181) ──────────────────────
    if (claimedForSend && claimDeliveryRecord) {
      await this.claimRepo.markScheduledReportClaimSent(
        { externalUserId: mapping.externalUserId, reportDate },
        claimLeaseToken,
      );
      return { ...ZERO, sent: 1 };
    }

    // ── Step 4: generate (inside claim window) ──────────────────────────────
    let reportText = opts.reportText;
    if (opts.generateReport) {
      try {
        reportText = await opts.generateReport();
      } catch (genError) {
        // Generation failed inside claim — release and let the classifier choose
        // durable retry versus a terminal/window-closed outcome.
        if (claimedForSend) {
          await this.claimRepo.releaseScheduledReportClaim(
            {
              externalUserId: mapping.externalUserId,
              reportDate,
            },
            claimLeaseToken,
          );
        }
        const classified = classifyError(genError);
        const shouldQueueRetry =
          classified.kind === 'retryable' ||
          (classified.kind === 'failure' && opts.classifyError === undefined);
        if (shouldQueueRetry && this.jobRepo) {
          const settings = this.reportSendScheduleService.getOutboxSettings();
          const nextRetryAt = new Date(
            Date.now() + settings.retryBackoffMinutes * 60 * 1000,
          );
          await this.jobRepo.recordRetryableFailure({
            platform,
            externalUserId: mapping.externalUserId,
            userId: mapping.userId,
            examDate: examDateForOutbox ?? '',
            firstAttemptDate: reportDate,
            maxRetries: settings.maxRetries,
            nextRetryAt,
            errorMessage: `Generation failed: ${classified.message}`,
          });
          return { ...ZERO, deferred: 1, retryQueued: 1 };
        }
        if (classified.kind === 'window_closed') {
          return { ...ZERO, windowClosed: 1 };
        }
        if (classified.kind === 'skipped') {
          return { ...ZERO, skipped: 1 };
        }
        return {
          ...ZERO,
          failures: [
            {
              externalUserId: mapping.externalUserId,
              error: classified.message,
            },
          ],
        };
      }
    }
    // ── Step 5: send ────────────────────────────────────────────────────
    try {
      const result = await this.delivery.sendReport({
        mapping,
        reportText,
        reportDate,
        deliveryKey,
      });

      if (result.ok) {
        if (claimedForSend) {
          await this.claimRepo.markScheduledReportClaimSent(
            {
              externalUserId: mapping.externalUserId,
              reportDate,
            },
            claimLeaseToken,
            'sent',
            deliveryKey,
            result.outcome ?? 'sent',
          );
        }
        if (examDateForOutbox && this.jobRepo) {
          await this.jobRepo.markSentByExternalUserExamDate(
            mapping.externalUserId,
            examDateForOutbox,
          );
        }
        return { ...ZERO, sent: 1 };
      }

      if (result.reason === 'RATE_LIMITED') {
        // The outbound cap is a deliberate containment decision, not a
        // transient provider failure. Burn this scheduled slot so the cron
        // and outbox cannot immediately replay the same report.
        if (claimedForSend) {
          await this.claimRepo.markScheduledReportClaimSent(
            {
              externalUserId: mapping.externalUserId,
              reportDate,
            },
            claimLeaseToken,
            undefined,
            deliveryKey,
            'rate_limited',
          );
        }
        return {
          ...ZERO,
          failures: [
            {
              externalUserId: mapping.externalUserId,
              error: 'outbound_rate_limited',
            },
          ],
        };
      }

      // ── Step 6: delivery failed — release + classify ──────────────────
      if (claimedForSend) {
        await this.claimRepo.releaseScheduledReportClaim(
          {
            externalUserId: mapping.externalUserId,
            reportDate,
          },
          claimLeaseToken,
        );
      }

      if (result.reason === 'RETRYABLE' && this.jobRepo) {
        const settings = this.reportSendScheduleService.getOutboxSettings();
        const nextRetryAt = new Date(
          Date.now() + settings.retryBackoffMinutes * 60 * 1000,
        );
        await this.jobRepo.recordRetryableFailure({
          platform,
          externalUserId: mapping.externalUserId,
          userId: mapping.userId,
          examDate: examDateForOutbox ?? '',
          firstAttemptDate: reportDate,
          maxRetries: settings.maxRetries,
          nextRetryAt,
          errorMessage: `Delivery failed: ${result.reason}`,
        });
        return { ...ZERO, deferred: 1, retryQueued: 1 };
      }

      if (result.reason === 'WINDOW_CLOSED') {
        return { ...ZERO, windowClosed: 1 };
      }
      if (result.reason === 'NOT_LINKED') {
        return { ...ZERO, skipped: 1 };
      }

      return {
        ...ZERO,
        failures: [
          {
            externalUserId: mapping.externalUserId,
            error: result.reason ?? 'DELIVERY_FAILED',
          },
        ],
      };
    } catch (error) {
      // ── Step 7: exception — release + classify ────────────────────────
      if (claimedForSend) {
        await this.claimRepo.releaseScheduledReportClaim(
          {
            externalUserId: mapping.externalUserId,
            reportDate,
          },
          claimLeaseToken,
        );
      }

      const classified = classifyError(error);

      if (classified.kind === 'retryable' && this.jobRepo) {
        const settings = this.reportSendScheduleService.getOutboxSettings();
        const nextRetryAt = new Date(
          Date.now() + settings.retryBackoffMinutes * 60 * 1000,
        );
        await this.jobRepo.recordRetryableFailure({
          platform,
          externalUserId: mapping.externalUserId,
          userId: mapping.userId,
          examDate: examDateForOutbox ?? '',
          firstAttemptDate: reportDate,
          maxRetries: settings.maxRetries,
          nextRetryAt,
          errorMessage: classified.message,
        });
        return { ...ZERO, deferred: 1, retryQueued: 1 };
      }

      if (classified.kind === 'window_closed') {
        return { ...ZERO, windowClosed: 1 };
      }
      if (classified.kind === 'skipped') {
        return { ...ZERO, skipped: 1 };
      }

      return {
        ...ZERO,
        failures: [
          { externalUserId: mapping.externalUserId, error: classified.message },
        ],
      };
    }
  }
}

function defaultClassifyError(error: unknown): ClassifiedError {
  return { kind: 'failure', message: errorMessage(error) };
}
