import { Inject, Injectable, Logger, Optional } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { errorMessage } from '@wispace/bot-common';
import { readReportClaimLeaseMs } from '@wispace/database';
import type { ReportClaimRepositoryPort } from '../ports/report-claim.repository.port';
import type { ReportDeliveryPort } from '../ports/report-delivery.port';
import type { ReportSendJobRepositoryPort } from '../ports/report-send-job.repository.port';
import { REPORT_CLAIM_REPOSITORY } from '../ports/report-claim.repository.port';
import { REPORT_DELIVERY_PORT } from '../ports/report-delivery.port';
import { REPORT_SEND_JOB_REPOSITORY } from '../ports/report-send-job.repository.port';
import type {
  ClaimAndSendResult,
  ReportMapping,
} from '../types/report-send-job.types';
import { ReportSendScheduleService } from './report-send-schedule.service';

const ZERO: ClaimAndSendResult = {
  sent: 0,
  skipped: 0,
  deferred: 0,
  windowClosed: 0,
  claimSkipped: 0,
  retryQueued: 0,
  failures: [],
};

export interface ClassifiedError {
  kind: 'retryable' | 'window_closed' | 'skipped' | 'failure';
  message: string;
}

/**
 * Shared claim lifecycle for scheduled report sends — used by Discord and Zalo.
 *
 * The skeleton is: hasSentToday guard → tryClaim → crash-recovery shortcircuit
 * → send → mark/release → error classify → retryable? record job.
 *
 * Platform-specific concerns are injected via callbacks:
 * - `classifyError`: maps exceptions to `{kind, message}`
 * - `platform`: for deliveryKey prefix and outbox
 * - `reportText`: pre-generated by caller (decouples generation from orchestration)
 */
@Injectable()
export class ReportOrchestrationService {
  private readonly logger = new Logger(ReportOrchestrationService.name);

  constructor(
    @Inject(REPORT_CLAIM_REPOSITORY)
    private readonly claimRepo: ReportClaimRepositoryPort,
    @Inject(REPORT_DELIVERY_PORT)
    private readonly delivery: ReportDeliveryPort,
    @Optional()
    @Inject(REPORT_SEND_JOB_REPOSITORY)
    private readonly jobRepo: ReportSendJobRepositoryPort | null,
    private readonly reportSendScheduleService: ReportSendScheduleService,
    private readonly configService: ConfigService,
  ) {}

  async claimAndSend(
    mapping: ReportMapping,
    opts: {
      reportDate: string;
      skipAlreadySentToday: boolean;
      reportText: string;
      examDateForOutbox?: string;
      classifyError?: (error: unknown) => ClassifiedError;
    },
  ): Promise<ClaimAndSendResult> {
    const { reportDate, skipAlreadySentToday, reportText, examDateForOutbox } =
      opts;
    const classifyError = opts.classifyError ?? defaultClassifyError;
    const platform = mapping.platform;
    const deliveryKey = `${platform}-report:${mapping.externalUserId}:${reportDate}`;

    // ── Step 1: has-sent-today guard ────────────────────────────────────
    if (skipAlreadySentToday) {
      const alreadySent = await this.claimRepo.hasSentScheduledReportToday(
        mapping.externalUserId,
      );
      if (alreadySent) {
        if (examDateForOutbox && this.jobRepo) {
          await this.jobRepo.markSentByExternalUserExamDate(
            mapping.externalUserId,
            examDateForOutbox,
          );
        }
        return { ...ZERO, skipped: 1 };
      }
    }

    // ── Step 2: try claim ───────────────────────────────────────────────
    let claimedForSend = false;
    let claimLeaseToken = '';
    let claimDeliveryRecord: string | undefined;
    if (skipAlreadySentToday) {
      const claimed = await this.claimRepo.tryClaimScheduledReport(
        {
          externalUserId: mapping.externalUserId,
          userId: mapping.userId,
          reportDate,
        },
        readReportClaimLeaseMs(this.configService),
      );
      if (!claimed.claimed || !claimed.leaseToken) {
        return { ...ZERO, claimSkipped: 1 };
      }
      claimedForSend = true;
      claimLeaseToken = claimed.leaseToken;
      claimDeliveryRecord =
        typeof claimed.deliveryRecord === 'string'
          ? claimed.deliveryRecord
          : undefined;
    }

    // ── Step 3: crash-recovery shortcircuit (#181) ──────────────────────
    if (claimedForSend && claimDeliveryRecord) {
      await this.claimRepo.markScheduledReportClaimSent(
        { externalUserId: mapping.externalUserId, reportDate },
        claimLeaseToken,
      );
      return { ...ZERO, sent: 1 };
    }

    // ── Step 4: send ────────────────────────────────────────────────────
    try {
      const result = await this.delivery.sendReport({
        mapping,
        reportText,
        reportDate,
        deliveryKey,
      });

      if (result.ok) {
        if (claimedForSend) {
          await this.claimRepo.markScheduledReportClaimSent(
            {
              externalUserId: mapping.externalUserId,
              reportDate,
            },
            claimLeaseToken,
            'sent',
            deliveryKey,
          );
        }
        if (examDateForOutbox && this.jobRepo) {
          await this.jobRepo.markSentByExternalUserExamDate(
            mapping.externalUserId,
            examDateForOutbox,
          );
        }
        return { ...ZERO, sent: 1 };
      }

      // ── Step 5: delivery failed — release + classify ──────────────────
      if (claimedForSend) {
        await this.claimRepo.releaseScheduledReportClaim(
          {
            externalUserId: mapping.externalUserId,
            reportDate,
          },
          claimLeaseToken,
        );
      }

      if (result.reason === 'RETRYABLE' && this.jobRepo) {
        const settings = this.reportSendScheduleService.getOutboxSettings();
        const nextRetryAt = new Date(
          Date.now() + settings.retryBackoffMinutes * 60 * 1000,
        );
        await this.jobRepo.recordRetryableFailure({
          platform,
          externalUserId: mapping.externalUserId,
          userId: mapping.userId,
          examDate: examDateForOutbox ?? '',
          firstAttemptDate: reportDate,
          maxRetries: settings.maxRetries,
          nextRetryAt,
          errorMessage: `Delivery failed: ${result.reason}`,
        });
        return { ...ZERO, deferred: 1, retryQueued: 1 };
      }

      return { ...ZERO, windowClosed: 1 };
    } catch (error) {
      // ── Step 6: exception — release + classify ────────────────────────
      if (claimedForSend) {
        await this.claimRepo.releaseScheduledReportClaim(
          {
            externalUserId: mapping.externalUserId,
            reportDate,
          },
          claimLeaseToken,
        );
      }

      const classified = classifyError(error);

      if (classified.kind === 'retryable' && this.jobRepo) {
        const settings = this.reportSendScheduleService.getOutboxSettings();
        const nextRetryAt = new Date(
          Date.now() + settings.retryBackoffMinutes * 60 * 1000,
        );
        await this.jobRepo.recordRetryableFailure({
          platform,
          externalUserId: mapping.externalUserId,
          userId: mapping.userId,
          examDate: examDateForOutbox ?? '',
          firstAttemptDate: reportDate,
          maxRetries: settings.maxRetries,
          nextRetryAt,
          errorMessage: classified.message,
        });
        return { ...ZERO, deferred: 1, retryQueued: 1 };
      }

      if (
        classified.kind === 'window_closed' ||
        classified.kind === 'skipped'
      ) {
        return { ...ZERO, windowClosed: 1 };
      }

      return {
        ...ZERO,
        failures: [
          { externalUserId: mapping.externalUserId, error: classified.message },
        ],
      };
    }
  }
}

function defaultClassifyError(error: unknown): ClassifiedError {
  return { kind: 'failure', message: errorMessage(error) };
}
