// Framework-free reschedule confirmation policy, contracts, and the in-memory
// store. TypeORM persistence and the recovery cron live in `adapters`.

export {
  RescheduleConfirmationService,
  RescheduleStageAbortedError,
  PENDING_RESCHEDULE_TTL_MS,
  RESCHEDULE_SCOPE_ERROR_MESSAGE,
  RESCHEDULE_CANCELLED_MESSAGE,
  RESCHEDULE_CANCEL_PROCESSING_MESSAGE,
  RESCHEDULE_CANCEL_NONE_MESSAGE,
  RESCHEDULE_EXPIRED_MESSAGE,
  RESCHEDULE_CONFIRM_TOKEN_REQUIRED_MESSAGE,
  RESCHEDULE_INVALID_TOKEN_MESSAGE,
  RescheduleScopeError,
  getRescheduleScopeFailureReason,
  assertRescheduleRecordOwnership,
  isValidApprovalToken,
  type CalendarEntryView,
  type StudyCalendarEntryView,
  type RescheduleResult,
  type RescheduleStudySessionResult,
  type StageInput,
  type StageResult,
  type ConfirmResult,
  type ConfirmError,
  type CalendarPort,
  type ReschedulePort,
  type CalendarCacheInvalidationPort,
  type RescheduleConfirmationOptions,
  type RescheduleScopeFailureReason,
} from '../reschedule-confirm.service';
export {
  MemoryRescheduleStore,
  type PendingRescheduleRecord,
  type RescheduleApprovalBinding,
  type RescheduleCancellationOutcome,
  type ReschedulePendingState,
  type RescheduleStorePort,
} from '../reschedule-store.port';
export {
  MemoryRescheduleAttemptStore,
  MAX_NOTIFICATION_ATTEMPTS,
  NOTIFICATION_RETRY_MS,
  applyNotificationOutcome,
  notificationIsDue,
  type BeginAttemptInput,
  type RescheduleAttemptRecord,
  type RescheduleAttemptStatus,
  type RescheduleAttemptStorePort,
  type RescheduleNotificationOutcome,
  type RescheduleNotificationStatus,
} from '../reschedule-attempt.port';
