export const STUDY_REMINDER_LLM_EXECUTION_PORT = Symbol(
  'STUDY_REMINDER_LLM_EXECUTION_PORT',
);
export const STUDY_REMINDER_LLM_USAGE_RECORDER_PORT = Symbol(
  'STUDY_REMINDER_LLM_USAGE_RECORDER_PORT',
);
